### ISSUE TITLE
NullPointerException in interactive export-csv-batch task 

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-tool#1]
If [8] export-csv-batch is selected from the interactive mode of SETTE, currently a NullPointerException is produced.

The problem is that it does not asks for the runner project tag.

These are the output to the console:

```
Selected: export-csv-batch
Snippet project: /home/sette/sette/sette-snippets/java/sette-snippets
Task: export-csv-batch
Tool: null
Runner project tag: null
Snippet selector: null
Runner timeout: 30000 ms
Backup policy: ASK
Exception: null
```

This is the exception:

```
java.lang.NullPointerException: null
        at hu.bme.mit.sette.core.tasks.CsvBatchGenerator.<init>(CsvBatchGenerator.java:52)
        at hu.bme.mit.sette.application.SetteApplication.execute(SetteApplication.java:227)
        at hu.bme.mit.sette.application.SetteApplicationMain.main(SetteApplicationMain.java:71)
```

This is the offending code:

```
this.runnerProjectTags = Stream.of(runnerProjectTags.split(",")).sorted()          
    .toArray(String[]::new);
```

If SETTE is started by the following command:

```
java -jar sette-all.jar --runner-project-tag run-01-30sec --snippet-project-dir  /home/sette/sette/sette-snippets/java/sette-snippets --task export-csv-batch
```

Then it results in a different exception:

```
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at hu.bme.mit.sette.application.SetteApplication.execute(SetteApplication.java:142)
```

Offending code:

```
String msg = String.format("The runner project tag is specified (%s) but for "
                            + "the %s task it is not required, thus it will not affect the "
                            + "current execution", runnerProjectTag);
```

Indeed, applicationTask  is missing from the end.

But this shows that runner project tag is not required for export-csv-batch, thus CsvBatchGenerator should be corrected.

**Comment by micskeiz** [comment]
Fixed in a4eba3ea2341d085cea9d04d15f8f924fe5aab07
